### ISSUE TITLE
Unhandled python exception in read callback: XMLSyntaxError

### ISSUE THREAD

**Issue by zottelbeyer** [fetzerch/fritzcollectd#12]
I get the following Error when my FritzBox is reset by Unitimedia:

    Unhandled python exception in read callback: XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 180 (line 1) 

On a Fritzbox 6490 Cable with FW 6.52. Seems to only be fixable by restarting collectd. Any ideas what might cause this and how to fix it?

**Comment by fetzerch** [comment]
I can catch that exception, but according to [collectd's documentation](https://collectd.org/documentation/manpages/collectd-python.5.shtml#writing_your_own_plugins) it should recover from this situation by skipping that plugin "for an increasing amount of time". Is this really not the case for you? Do you have to restart your Fritzbox as well so that it starts sending proper responses again?

**Comment by zottelbeyer** [comment]
collectd does exactly what you described but it doesn't seem to restart the plugin without restarting collectd entirely:

    Mar 23 04:31:15 fileserver collectd[24201]: Unhandled python exception in read callback: XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 180 (line 1)
    Mar 23 04:31:15 fileserver collectd[24201]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.
    Mar 23 04:31:15 fileserver collectd[24201]: plugin_read_thread: read-function of the `python.fritzcollectd' plugin took 33.514 seconds, which is above its read interval (20.000 seconds). You might want to adjust the `Interval' or `ReadThreads' settings.
    Mar 23 04:31:49 fileserver collectd[24201]: Unhandled python exception in read callback: XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 180 (line 1)
    Mar 23 04:31:49 fileserver collectd[24201]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 40.000 seconds.
    Mar 23 04:32:29 fileserver collectd[24201]: Unhandled python exception in read callback: XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and BODY, line 1, column 180 (line 1)
    Mar 23 04:32:29 fileserver collectd[24201]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 80.000 seconds.

Only after restarting collectd does the Grafana Dashboard work again. It might be an issue with influxd / Grafana though?

**Comment by fetzerch** [comment]
Ok that means collectd is indeed calling read again, but the connection seems to be non functional.
Can you try the following change please: https://github.com/fetzerch/fritzcollectd/commit/f81a489640ad356d83ff377ddd4fcb45754b748b, that reconnects if such an error occurs. I'm not sure if the box answers fast enough after a reset, but let's try:

```
sudo pip install --upgrade https://github.com/fetzerch/fritzcollectd/archive/xmlsyntaxerror.zip
```

**Comment by fetzerch** [comment]
I've released the fix (https://github.com/fetzerch/fritzcollectd/commit/a4379c5f085dfb8ded4b2dde8ee971845cc1cd38) now as part of `fritzcollectd-0.6.0`.
