### ISSUE TITLE
Getting data of energy consumption and temperature of FritzBox

### ISSUE THREAD

**Issue by jostrasser** [fetzerch/fritzcollectd#17]
Hi,

Can you integrate a function to get the data of the energy consumption and temperature of the FritzBox?

Many thanks JO!

**Comment by fetzerch** [comment]
It's possible to add whatever the [TR-064 API](https://avm.de/service/schnittstellen/) offers.
I wasn't able to find any info regarding consuption or temperature. Are you sure they can be accessed?

**Comment by jostrasser** [comment]
Hi,
I‘m sorry, they are missing on the API. 
I only can see it on the Admin-UI. 

I will contact AVM support to open a feature request. 

Thanks JO!
