### ISSUE TITLE
Unhandled python exception in init callback: XMLSyntaxError

### ISSUE THREAD

**Issue by carlolf** [fetzerch/fritzcollectd#21]
with trace on, I see this stacktrace: 
`Okt 18 16:08:49 Pluto collectd[3694]: Unhandled python exception in init callback: XMLSyntaxError: Document is empty, line 1, column 1 (line 1)
Okt 18 16:08:49 Pluto collectd[3694]: Traceback (most recent call last):
Okt 18 16:08:49 Pluto collectd[3694]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd/__init__.py", line 294, in callback_init
                                          config.init()
Okt 18 16:08:49 Pluto collectd[3694]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd/__init__.py", line 146, in init
                                          user=self._fritz_user)
Okt 18 16:08:49 Pluto collectd[3694]:   File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzconnection.py", line 323, in __init__
                                          self._read_descriptions(password)
Okt 18 16:08:49 Pluto collectd[3694]:   File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzconnection.py", line 335, in _read_descriptions
                                          parser = FritzDescParser(self.address, self.port, descfile)
Okt 18 16:08:49 Pluto collectd[3694]:   File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzconnection.py", line 194, in __init__
                                          tree = etree.parse(source)
Okt 18 16:08:49 Pluto collectd[3694]:   File "src/lxml/etree.pyx", line 3426, in lxml.etree.parse
Okt 18 16:08:49 Pluto collectd[3694]:   File "src/lxml/parser.pxi", line 1839, in lxml.etree._parseDocument
Okt 18 16:08:49 Pluto collectd[3694]:   File "src/lxml/parser.pxi", line 1865, in lxml.etree._parseDocumentFromURL
Okt 18 16:08:49 Pluto collectd[3694]:   File "src/lxml/parser.pxi", line 1769, in lxml.etree._parseDocFromFile
Okt 18 16:08:49 Pluto collectd[3694]:   File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFile
Okt 18 16:08:49 Pluto collectd[3694]:   File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
Okt 18 16:08:49 Pluto collectd[3694]:   File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
Okt 18 16:08:49 Pluto collectd[3694]:   File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError
Okt 18 16:08:49 Pluto collectd[3694]: XMLSyntaxError: Document is empty, line 1, column 1 (line 1)
`
I am quite unsure if this is an effect of the Fritz Box not answering request or if it is an error somewhere else.
This is my config:
`<Plugin python>
    Import "fritzcollectd"
	LogTraces true
    <Module fritzcollectd>
        Address "fritz.box"
        Port 8089
        User "collectLog"
        Password "xxxxxxxxxxx"
        Hostname "FritzBox"
        Instance "1"
        Verbose "True"
    </Module>`

**Comment by fetzerch** [comment]
Can you check that the password is correct and the `collectLog` user has the `FRITZ!Box Settings` permission? See: https://github.com/fetzerch/fritzcollectd#prerequisites
Also what version of `fritzcollectd` do you use?

**Comment by carlolf** [comment]
Hi fetzerch,
I use the latest version of fritzcollectd. I gave the user 'collectLog' the required permissions. If I do this call
`carlo@Pluto:~$ python /usr/local/lib/python2.7/dist-packages/fritzconnection/fritzstatus.py`
it gives:
`FritzStatus:
version:            0.5.1
model:              FRITZ!Box 6490 Cable (kdg)
is linked:          False
is connected:       False
external ip:        192.168.178.1
uptime:             00:00:00
bytes send:         0
bytes received:     0
max. bit rate:      ('6.1 MBit/s', '101.1 MBit/s')
`
I think this shows that fritzcollectd can connect? 
Is it possible the my Fritzbox (which is from KabelDeutschland) returns an empty document to the request and the parser stumbles over this with an exception?

**Comment by carlolf** [comment]
Finally, I found the cause of the exception. I used port 8089 in the configuration for 'collectd', because the Fritzbox reports this :
`
8089 | TCP, IPv4 | Anbieter-Dienste (TR069)
-- | -- | --
` 
Switching the port to the default 49000 indeed stopped raising the exception.

So, this is another succesful step for running Grafana as report tool, described at [](https://blog.butenostfreesen.de/2018/10/11/Fritz-Box-Monitoring-mit-Grafana-und-Raspberry/).

I now have to solve that influxdb tables have no data. :-1:

**Comment by fetzerch** [comment]
Cool, thanks for reporting back.

Others have mentioned that due to some queries, it can take a while until grafana shows all graphs.
Make sure also to play with the zoom. In my dashboard the default is last 7 days, for the beginning you might want to set it to 1-2 days.

**Comment by carlolf** [comment]
Thanks also for answering to my problems.

To be more exact on failures, I think the script should check if there was a real connection to Fritzbox on the given port with a valid result before calling the Xml-Parser.
