### ISSUE TITLE
Error: Unhandled python exception in read callback

### ISSUE THREAD

**Issue by fetzerch** [fetzerch/fritzcollectd#3]
@janvonde: Thanks your message, I'll move this to the project's issue tracker

---

I am trying to get this up and running, but I am getting the following errors:

> Oct 20 10:54:35 hs2 collectd[30080]: Unhandled python exception in read callback: KeyError: 'GetAddonInfos'
Oct 20 10:54:35 hs2 collectd[30080]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.
Oct 20 10:54:55 hs2 collectd[30080]: Unhandled python exception in read callback: KeyError: 'GetAddonInfos'
Oct 20 10:54:55 hs2 collectd[30080]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 40.000 seconds.

I installed fritzcollectd, fritzconnection and collectd via pip on a Ubuntu Linux 16.04 box. At collectd I set the ModulePath for the python plugin to /usr/local/lib/python2.7/dist-packages/. The following files are there:

>✓  root@hs2 ~ $ ll /usr/local/lib/python2.7/dist-packages/
insgesamt 68K
drwxr-sr-x 2 root staff 4.0K Okt 20 09:37 collectd-1.0.dist-info/
-rw-r--r-- 1 root staff 6.7K Okt 20 09:37 collectd.py
-rw-r--r-- 1 root staff 9.0K Okt 20 09:37 collectd.pyc
drwxr-sr-x 2 root staff 4.0K Okt 20 10:48 fritzcollectd-0.2.0.dist-info/
-rw-r--r-- 1 root staff 6.0K Okt 20 10:48 fritzcollectd.py
-rw-r--r-- 1 root staff 6.0K Okt 20 10:48 fritzcollectd.pyc
drwxr-sr-x 2 root staff 4.0K Okt 20 09:23 fritzconnection/
drwxr-sr-x 2 root staff 4.0K Okt 20 09:23 fritzconnection-0.4.6.dist-info/
drwxr-sr-x 6 root staff 4.0K Okt 20 09:23 lxml/
drwxr-sr-x 2 root staff 4.0K Okt 20 09:23 lxml-3.6.4.dist-info/
drwxr-sr-x 3 root staff 4.0K Okt 20 09:23 requests/
drwxr-sr-x 2 root staff 4.0K Okt 20 09:23 requests-2.11.1.dist-info/
✓  root@hs2 ~ $ 

When I try to run the python file directly I am getting the following error:
>✓  root@hs2 /usr/local/lib/python2.7/dist-packages $ python fritzcollectd.py
Traceback (most recent call last):
  File "fritzcollectd.py", line 157, in <module>
    collectd.register_config(FC.callback_configure)
AttributeError: 'module' object has no attribute 'register_config'
⚠  root@hs2 /usr/local/lib/python2.7/dist-packages $ 

Do you have an idea what could be wrong in my setup?

Thanks for this great module and for your time,

Jan

**Comment by janvonde** [comment]
@fetzerch Thanks for your help. I think I had a problem with my python puppet setup first, but still it is not working. My collectd config is:

```
<LoadPlugin python>
    Globals true
</LoadPlugin>

<Plugin "python">
    ModulePath "/usr/local/lib/python2.7/dist-packages/"
    ModulePath "/usr/share/collectd/python"
    LogTraces false
    Interactive false
    Import "fritzcollectd"
    <Module "fritzcollectd">
        Address "192.168.179.1"
        Hostname "Fritz!Box"
        Instance "1"
        Password "XXX"
        Port "49000"
        User "fritzcollectd"
    </Module>
</Plugin>
```

fritzstatus.py is working:
> ✓  root@hs2 ~ $ python /usr/local/lib/python2.7/dist-packages/fritzconnection/fritzstatus.py
FritzStatus:
version:            0.4.5
model:              FRITZ!Box 7490
is linked:          True
is connected:       True
external ip:        1.2.3.4
uptime:             18:25:02
bytes send:         3086905346
bytes received:     5290830636
max. bit rate:      ('29.0 MBit/s', '89.0 MBit/s')
✓  root@hs2 ~ $ 

The current error message I am getting after starting collectd is:
>Oct 21 21:24:40 hs2 systemd[1]: Started Statistics collection and monitoring daemon.
Oct 21 21:24:41 hs2 collectd[18164]: Initialization complete, entering read-loop.
Oct 21 21:24:41 hs2 collectd[18164]: tcpconns plugin: Reading from netlink succeeded. Will use the netlink method from now on.
Oct 21 21:24:41 hs2 collectd[18164]: Unhandled python exception in read callback: TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
Oct 21 21:24:41 hs2 collectd[18164]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.

Thank you for your help and time!

**Comment by janvonde** [comment]
Sorry, the last error was my fault because I tried to look into the python script myself. It is still

>Oct 21 21:36:18 hs2 collectd[19971]: Unhandled python exception in read callback: KeyError: 'GetAddonInfos'
Oct 21 21:36:18 hs2 collectd[19971]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.

**Comment by fetzerch** [comment]
Could you set `LogTraces true`, that should help getting a strack trace and we see exactly where it fails.

**Comment by janvonde** [comment]
Here you are:
>Oct 21 21:40:28 hs2 collectd[20642]: Unhandled python exception in read callback: KeyError: 'GetAddonInfos'
Oct 21 21:40:28 hs2 collectd[20642]: Traceback (most recent call last):
Oct 21 21:40:28 hs2 collectd[20642]:   File "/usr/share/collectd/python/fritzcollectd.py", line 102, in callback_read#012    values = self.fritz_read_data()
Oct 21 21:40:28 hs2 collectd[20642]:   File "/usr/share/collectd/python/fritzcollectd.py", line 143, in fritz_read_data#012    values.update(self._fc.call_action(service, action))
Oct 21 21:40:28 hs2 collectd[20642]:   File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzconnection.py", line 361, in call_action#012    action = self.services[service_name].actions[action_name]
Oct 21 21:40:28 hs2 collectd[20642]: KeyError: 'GetAddonInfos'
Oct 21 21:40:28 hs2 collectd[20642]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.

**Comment by fetzerch** [comment]
Ok, it seems to be caused by fritzconnection 0.4.6. If you install 0.4.5 (`pip install fritzconnection==0.4.5`) it should work for the moment. I'll have a look what causes this incompatibility.

**Comment by janvonde** [comment]
Thanks for your quick response, but I am afraid it doesn't solve the problem  :confused:

>✓  root@hs2 ~ $ pip install fritzconnection==0.4.5
Collecting fritzconnection==0.4.5
  Downloading fritzconnection-0.4.5.tar.gz
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.2.5 in /usr/local/lib/python2.7/dist-packages (from fritzconnection==0.4.5)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.2.0 in /usr/local/lib/python2.7/dist-packages (from fritzconnection==0.4.5)
Building wheels for collected packages: fritzconnection
  Running setup.py bdist_wheel for fritzconnection ... done
  Stored in directory: /root/.cache/pip/wheels/6d/08/f3/72fd09d5145092fe89b1e84b7e55b630865d6b6759c4bd44b5
Successfully built fritzconnection
Installing collected packages: fritzconnection
  Found existing installation: fritzconnection 0.4.6
    Uninstalling fritzconnection-0.4.6:
      Successfully uninstalled fritzconnection-0.4.6
Successfully installed fritzconnection-0.4.5
✓  root@hs2 ~ $ service collectd restart && tailf /var/log/syslog
Oct 21 22:09:55 hs2 collectd[25040]: plugin_load: plugin "network" successfully loaded.
Oct 21 22:09:55 hs2 collectd[25040]: plugin_load: plugin "processes" successfully loaded.
Oct 21 22:09:55 hs2 collectd[25040]: plugin_load: plugin "python" successfully loaded.
Oct 21 22:09:55 hs2 collectd[25040]: plugin_load: plugin "swap" successfully loaded.
Oct 21 22:09:55 hs2 collectd[25040]: plugin_load: plugin "tail" successfully loaded.
Oct 21 22:09:55 hs2 collectd[25040]: plugin_load: plugin "tcpconns" successfully loaded.
Oct 21 22:09:55 hs2 collectd[25040]: plugin_load: plugin "uptime" successfully loaded.
Oct 21 22:09:55 hs2 collectd[25040]: plugin_load: plugin "users" successfully loaded.
Oct 21 22:09:56 hs2 collectd[25040]: Systemd detected, trying to signal readyness.
Oct 21 22:09:56 hs2 systemd[1]: Started Statistics collection and monitoring daemon.
Oct 21 22:09:56 hs2 collectd[25040]: Initialization complete, entering read-loop.
Oct 21 22:09:56 hs2 collectd[25040]: tcpconns plugin: Reading from netlink succeeded. Will use the netlink method from now on.
Oct 21 22:09:56 hs2 collectd[25040]: Unhandled python exception in read callback: KeyError: 'GetAddonInfos'
Oct 21 22:09:56 hs2 collectd[25040]: Traceback (most recent call last):
Oct 21 22:09:56 hs2 collectd[25040]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd.py", line 102, in callback_read#012    values = self.fritz_read_data()
Oct 21 22:09:56 hs2 collectd[25040]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd.py", line 143, in fritz_read_data#012    values.update(self._fc.call_action(service, action))
Oct 21 22:09:56 hs2 collectd[25040]:   File "/usr/local/lib/python2.7/dist-packages/fritzconnection/fritzconnection.py", line 361, in call_action#012    action = self.services[service_name].actions[action_name]
Oct 21 22:09:56 hs2 collectd[25040]: KeyError: 'GetAddonInfos'
Oct 21 22:09:56 hs2 collectd[25040]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.
^C
⚠  root@hs2 ~ $

**Comment by fetzerch** [comment]
:/ I was able to reproduce it for a moment, after upgrading to 0.4.6. I switched again to 0.4.5 and it worked, but the second time upgrading to 0.4.6 it didn't change anything. It's still working.

Another idea for now might be to catch the exception, but then you won't get all vales.

```
--- a/fritzcollectd.py
+++ b/fritzcollectd.py
@@ -140,7 +140,10 @@ class FritzCollectd(object):

         # Combine all values available in SERVICE_ACTIONS into a dict
         for service, action in self.SERVICE_ACTIONS:
-            values.update(self._fc.call_action(service, action))
+            try:
+                values.update(self._fc.call_action(service, action))
+            except KeyError:
+                pass

         # Construct a dict: {instance: (value_type, value)} from the queried
         # results applying a conversion (if defined)
```

I'll still try to reproduce it.

**Comment by janvonde** [comment]
After applying the patch I am getting a new type of error:

>Oct 21 22:31:29 hs2 collectd[29630]: Unhandled python exception in read callback: TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
Oct 21 22:31:29 hs2 collectd[29630]: Traceback (most recent call last):
Oct 21 22:31:29 hs2 collectd[29630]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd.py", line 102, in callback_read#012    values = self.fritz_read_data()
Oct 21 22:31:29 hs2 collectd[29630]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd.py", line 153, in fritz_read_data#012    for key, (instance, value_type) in self.VALUES.items()
Oct 21 22:31:29 hs2 collectd[29630]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd.py", line 153, in <dictcomp>#012    for key, (instance, value_type) in self.VALUES.items()
Oct 21 22:31:29 hs2 collectd[29630]:   File "/usr/local/lib/python2.7/dist-packages/fritzcollectd.py", line 59, in <lambda>#012    'NewByteReceiveRate': lambda x: 8 * x
Oct 21 22:31:29 hs2 collectd[29630]: TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
Oct 21 22:31:29 hs2 collectd[29630]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 20.000 seconds.

I'll look tomorrow morning if i can get the error reproduceable in a vagrant box.

**Comment by fetzerch** [comment]
I've checked the settings on the box itself and if I disable transmitting status info via upnp (german: "Statusinformationen über UPnP übertragen" in network overview -> settings) I get exactly the same errors. Can you check if that is enabled on your box?

**Comment by janvonde** [comment]
@fetzerch first I was embarrassed that this could be the case, but I checked it and everything is enabled. As you saw I'v got a Fritz!Box 7490

**Comment by fetzerch** [comment]
I've got the same box, but slightly newer firmware from what I can see.
Another way of reproducing it here is if I set both `User` and `Password` in the config and set `User` to an incorrect value (you set it to `fritzcollectd` in your config. Not sure if/how you set the username on the box). Can you please check if it works if you simply comment both out.

**Comment by janvonde** [comment]
@fetzerch the truth is, that if I remove all settings except the IP address, that it seems to work for me. No idea why. 

I think this issue can be closed. The issue with the disabled UPNP and the username and passwort could be written to the readme maybe. Do you want me to open a pull request for that?

Last thing: would you mind sharing your grafana fritzbox dashboard somewhere?

**Comment by fetzerch** [comment]
Great that it works now. Don't worry, I'll update the readme. I've The dashboard is now available here: https://grafana.net/dashboards/713
