### ISSUE TITLE
wrong data

### ISSUE THREAD

**Issue by itsNik** [fetzerch/fritzcollectd#30]
Hello everyone,

I use fritzcollectd together with influxdb and this grafana dashboard: https://grafana.com/dashboards/713
I noticed that the data is is not collected correctly. For example the my "Total Download" value is always lower than my "Last 24h Download" value. Total Download Value is about 15GB and should be over 200GB. All the stats seem to be incorrent and I'm not sure if this is a fritzcollectd problem or if the grafana querries are incorrect.

**Comment by jostrasser** [comment]
Looks similar in my case if I compare the values with the Fritzbox directly. 

In Grafana I have transferred 85GB this month, on the Fritzbox 550GB. 

To display the actual throughout in Grafana takes a while and is a little bit delayed but this is normal. 
I think the displayed values are okay.

**Comment by fetzerch** [comment]
Could you please have a look at [dasboard revision 5](https://grafana.com/api/dashboards/713/revisions/5/download)? I've improved the queries and the values are not much closer to what's displayed in the Fritzbox webui.

Additionally please keep in mind that the "Total Download" takes "Grafana's range selection" into account while "Last 24h" is always the last 24 hours. --> If you select "Last 24 hours" in the range selection, you should now see the same values.
