### ISSUE TITLE
compatibility with fritzconnection

### ISSUE THREAD

**Issue by kbr** [fetzerch/fritzcollectd#32]
There has been a bugfix in fritzconnection 0.8.0 that prevents to run fritzcollectd without a modification. So I recommend to change the requirements to:

fritzconnection>=0.6.0,<0.8.0

**Comment by fetzerch** [comment]
Thanks for reporting. Closing as duplicate of #31. I've quickly released v0.6.3 with your suggestion. A proper fix has to wait until I find time to look into the change in fritzconnection more thoroughly.

**Comment by Apollon77** [comment]
Why this is an adapter request? Please create the issue in the relevant Adapter repo.
