### ISSUE TITLE
Werte in Grafana Dashboard für Upload/Download falsch

### ISSUE THREAD

**Issue by volschin** [fetzerch/fritzcollectd#41]
Die Werte des Dashboards sind leider falsch ermittelt, wie mir der Vergleich mit meiner Fritzbox sagt. Ich habe mich daber auf die Suche gemacht und bin auch fündig geworden.
https://grafana.com/grafana/dashboards/10488

[FRITZ!Box Router Status-1580061829319.txt](https://github.com/fetzerch/fritzcollectd/files/4113954/FRITZ.Box.Router.Status-1580061829319.txt)

**Comment by fetzerch** [comment]
Danke. Ich habe das Dashboard aktualisiert: https://grafana.com/api/dashboards/713/revisions/5/download. Die Werte sind nun näher an dem was die Fritzbox anzeigt.

**Comment by SuperSandro2000** [comment]
Wenn ich nichts verstellt habe, dann war vorher der Total Upload um 60 GB (!) falsch und der Total Download um 30 GB.

Außerdem finde ich die neuen Graphen für und Gauges sehr viel hübscher.
Danke!

Noch eine Frage: Wie kann ich in zukunft das Dashboard updaten, ohne ein neues anzulegen?

**Comment by fetzerch** [comment]
> Wenn ich nichts verstellt habe, dann war vorher der Total Upload um 60 GB (!) falsch und der Total > Download um 30 GB.
>
> Außerdem finde ich die neuen Graphen für und Gauges sehr viel hübscher.
> Danke!

Schön zu hören.

> Noch eine Frage: Wie kann ich in zukunft das Dashboard updaten, ohne ein neues anzulegen?

Da hab ich leider keine bessere Lösung. Evtl müsstest du das mal mit der API (oder [Wizzy](https://grafana-wizzy.com/remote-commands/dashboard-commands/)) probieren.
