### ISSUE TITLE
data are lost

### ISSUE THREAD

**Issue by JerryPenguin** [fetzerch/fritzcollectd#42]
With large downloads, fritzcollectd chokes and seems to pass on only a fraction of the data to collectd.
My FritzBox statistics or the greetings of the downloads and uploads are many times larger than the values displayed in Grafana.

**Comment by fetzerch** [comment]
Have you tried [revision 5](https://grafana.com/api/dashboards/713/revisions/5/download) of the dashboard?

The upload/download counters in the Fritzbox API wrap at 4 GB and getting them to display correctly with InfluxDB and Grafana seems to be tricky.

**Comment by JerryPenguin** [comment]
Thank you very much for your quick answer and solution.

I just tested the Rev. 5 and it seems to work.
I have done a big up- and download of more than 4GB and both are now displayed correctly.

Great support :-)
Thanks a lot
