### ISSUE TITLE
After Fritz OS Upgrade fritzcollectd stopped working

### ISSUE THREAD

**Issue by Niemand112233** [fetzerch/fritzcollectd#47]
Hi,

after an Fritz OS Upgrade to 7.12 fritzcollectd stopped working. How to resolve?

**Comment by volschin** [comment]
Generally FritzOS 7.12 and 7.19 Beta show no problem. What is your log saying.

**Comment by Niemand112233** [comment]
I resolved it: it was a problem with collectd. I had to restart it. I don't know why this happened during Upgrade to 7.12. Strange.
