### ISSUE TITLE
Unknown Action: GetAddonInfos

### ISSUE THREAD

**Issue by Apollon77** [fetzerch/fritzcollectd#5]
Hi,

I wanted to use this with my Fritzbox 3490 and get the following error:

Unhandled python exception in read callback: ActionError: Unknown Action: GetAddonInfos

Also in the official AVM TR-064 document this Action is not in ...

**Comment by Apollon77** [comment]
... und wenn ich die eine Zeile auskommentiere kommt:

Unhandled python exception in read callback: TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by fetzerch** [comment]
This looks like a similar issue to what has been reported in https://github.com/fetzerch/fritzcollectd/issues/3. Please try to follow the steps in the comments starting from https://github.com/fetzerch/fritzcollectd/issues/3#issuecomment-255460591.

**Comment by Apollon77** [comment]
Yes, worked now! what is the best "Interval" to query the Fritzbox ... I think the collectd stardard 10s is a bit too fast, or ?! Are there experiences? Would also be a good Info for readme

**Comment by fetzerch** [comment]
Personally I do use it with the default setting of 10s, but you're welcome to try different levels and report back what works best for you.

**Comment by Apollon77** [comment]
I now also use with 10sec and no problems ... great!
