### ISSUE TITLE
Any way to also log "LAN traffic"?

### ISSUE THREAD

**Issue by Apollon77** [fetzerch/fritzcollectd#6]
The plugin is great to seee the WAN traffic ... But with Fritzbox as the main router for the home network also internal traffic statistics would be cool, or ?!

**Comment by fetzerch** [comment]
Yes, this is possible. Unfortunately the necessary call only works when specifying a password but there's currently an issue with that (https://github.com/fetzerch/fritzcollectd/issues/9#issuecomment-285879959) and that has to be fixed first.

Also there are no port/host based statistics, only for LAN as a whole.

For reference:
```
import fritzconnection

fc = fritzconnection.FritzConnection(fritzconnection.fritzconnection.FRITZ_IP_ADDRESS, fritzconnection.fritzconnection.FRITZ_TCP_PORT, password="xxxxxxx")
print(fc.call_action("LANEthernetInterfaceConfig", "GetStatistics"))

{'NewPacketsReceived': 40780,
 'NewBytesSent': 19112957,
 'NewPacketsSent': 55472,
 'NewBytesReceived': 4254219}
```

**Comment by Apollon77** [comment]
cool, yes I discovered #9 too ...

**Comment by Apollon77** [comment]
cool  testbar wieder über den update-Install vom Git?

**Comment by fetzerch** [comment]
PyPi already has version 0.4.0, so you can just upgrade using pip. Note that lan stats require to have a password configured.

**Comment by Apollon77** [comment]
Works, great, thank you!
