### ISSUE TITLE
Error importing module "fritzcollectd"

### ISSUE THREAD

**Issue by derjungewilde** [fetzerch/fritzcollectd#8]
Hi I try to get it to work but when I start the collectd I get the following message:

<img width="1286" alt="alex_userver____ _ssh_alex_192_168_0_200_ _200x58" src="https://cloud.githubusercontent.com/assets/4105139/23234261/c9d8a5c0-f951-11e6-8895-097e9fc6dd23.png">
<img width="563" alt="collectd_conf_ ___desktop" src="https://cloud.githubusercontent.com/assets/4105139/23234375/34bb43ac-f952-11e6-9acd-ecca2841f440.png">

**Comment by fetzerch** [comment]
Make sure lxml and requests are installed: `pip install lxml requests`.
They should have been installed automatically when you install fritzcollectd via pip.

**Comment by derjungewilde** [comment]
yes both are installed

<img width="871" alt="alex_userver____ _ssh_alex_192_168_0_200_ _200x58" src="https://cloud.githubusercontent.com/assets/4105139/23248267/c39131d0-f99e-11e6-9aff-086f3b5bb492.png">

**Comment by fetzerch** [comment]
Please try to uninstall requests and install it again as root. It seems to be installed in `.local/...` which works for your user, but not for the user collectd is running as.
Then it also should work without specifying the ModulePath. For me, this simple config is enough:

```
<LoadPlugin python>
        Globals true
</LoadPlugin>
<Plugin python>
        Import "fritzcollectd"
        <Module fritzcollectd>
                Hostname "router"
        </Module>
</Plugin>
```

**Comment by derjungewilde** [comment]
ok I will try. Only requests or the hole fritzcollectd?

**Comment by derjungewilde** [comment]
ok is working now. 

I uninstalled fritzcollectd and installed it as root again. After that I changed my plugin config to your version above and now it's working.

Thanks for your help.
