### ISSUE TITLE
Unhandled python exception in read callback: ActionError: Unknown Action: GetAddonInfos

### ISSUE THREAD

**Issue by mblaschke** [fetzerch/fritzcollectd#9]
After one month i'm getting this error now since 2 or 3 weeks:

```
collectd[11918]: Unhandled python exception in read callback: ActionError: Unknown Action: GetAddonInfos
collectd[11918]: read-function of plugin `python.fritzcollectd' failed. Will suspend it for 120.000 seconds.
```

FritzBox 7490

Maybe sincee the last fritzbox update but i'm not sure.

**Comment by fetzerch** [comment]
https://github.com/fetzerch/fritzcollectd/issues/3#issuecomment-255460591
Either status info via upnp disabled, or wrong user/password combination. It should work fine without user/pass btw.

**Comment by mblaschke** [comment]
With `fritzconnection` i can connect and list the services.
only a few without user/pass
all services with same user/pass

Currently i'm not getting any stats without user/pass.. still trying to get some error messages.

**Comment by mblaschke** [comment]
Forgot to reenable `Hostname` (`Address` was always enabled) in configuration, now at least i'm getting basic informations.

**Comment by fetzerch** [comment]
After digging a bit into this, it seems that `'WANCommonInterfaceConfig:1': 'GetAddonInfos'` only works without password. (FRITZ!OS: 06.80). Is that the same for you? Unfortunately the rates seem to be only available through `GetAddonInfos`. For the bytes counters there are alternative actions available: `GetTotalBytesSent`, `GetTotalBytesReceived`.

Is that the same on your box?
Looks like a bug in the box to me, I'll try to contact AVM.

For the moment that means the whole plugin only works without specifying a password.

**Comment by Apollon77** [comment]
happens for me on a 6.80 box (7490) and also a 6360 box with 6.52 (unitymedia) ... so seems not like a "Bug" and even if ... no one knows if fixable by people (e.g. with the unitymedia box where updates are only done by the provider) :-(

So why for now not implement it working and react if AVM fixes it to get configurable or retried when errored

**Comment by Apollon77** [comment]
0.4.0 verified
